[project]
name = "nova-simulators-python-tests"
version = "0.1.0"
description = "Python client tests for Nova Simulators"
requires-python = ">=3.8"
dependencies = [
    "requests>=2.31.0",
    "pytest>=7.4.3",
]

[tool.hatch.build.targets.wheel]
packages = ["."]
